In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import GradientBoostingRegressor

In [37]:
df = pd.read_csv("/Users/imac/DAT07-28-AG/ClassMaterial/Unit3/data/iowa_train2.csv")

In [38]:
df.head()

,Id,MSSubClass,MSZoning,LotArea,Neighborhood,OverallQual,OverallCond,YearBuilt,GrLivArea,1stFlrSF,2ndFlrSF,GrLivArea.1,FullBath,HalfBath,GarageType,GarageYrBlt,GarageFinish,GarageCars,SalePrice
0,1,60,RL,8450,CollgCr,7,5,2003,1710,856,854,1710,2,1,Attchd,2003.0,RFn,2,208500
1,2,20,RL,9600,Veenker,6,8,1976,1262,1262,0,1262,2,0,Attchd,1976.0,RFn,2,181500
2,3,60,RL,11250,CollgCr,7,5,2001,1786,920,866,1786,2,1,Attchd,2001.0,RFn,2,223500
3,4,70,RL,9550,Crawfor,7,5,1915,1717,961,756,1717,1,0,Detchd,1998.0,Unf,3,140000
4,5,60,RL,14260,NoRidge,8,5,2000,2198,1145,1053,2198,2,1,Attchd,2000.0,RFn,3,250000

In [39]:
missing_cols_query = df.isnull().sum() > 0
missing_cols_num = df.loc[:, missing_cols_query].select_dtypes(include=np.number).columns.tolist()
missing_cols_cat = df.loc[:, missing_cols_query].select_dtypes(include=np.object).columns.tolist()
df[missing_cols_num] = df[missing_cols_num].fillna(0)
df[missing_cols_cat] = df[missing_cols_cat].fillna("None")

In [41]:
# declare X and y
X = df.drop("SalePrice", axis=1)
y = df["SalePrice"]

# X = pd.get_dummies(X)

In [15]:
X.head()

,Id,MSSubClass,LotArea,OverallQual,OverallCond,YearBuilt,GrLivArea,1stFlrSF,2ndFlrSF,GrLivArea.1,...,GarageType_Attchd,GarageType_Basment,GarageType_BuiltIn,GarageType_CarPort,GarageType_Detchd,GarageType_None,GarageFinish_Fin,GarageFinish_None,GarageFinish_RFn,GarageFinish_Unf
0,1,60,8450,7,5,2003,1710,856,854,1710,...,1,0,0,0,0,0,0,0,1,0
1,2,20,9600,6,8,1976,1262,1262,0,1262,...,1,0,0,0,0,0,0,0,1,0
2,3,60,11250,7,5,2001,1786,920,866,1786,...,1,0,0,0,0,0,0,0,1,0
3,4,70,9550,7,5,1915,1717,961,756,1717,...,0,0,0,0,1,0,0,0,0,1
4,5,60,14260,8,5,2000,2198,1145,1053,2198,...,1,0,0,0,0,0,0,0,1,0

In [16]:
gbm = GradientBoostingRegressor()
gbm.fit(X, y)

GradientBoostingRegressor()

In [17]:
gbm.score(X, y)

0.9425747494676331

In [42]:
# split your data into training and test sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1985)

In [20]:
X_train.shape

(1168, 55)

In [21]:
X_test.shape

(292, 55)

In [22]:
X_train.head()

,Id,MSSubClass,LotArea,OverallQual,OverallCond,YearBuilt,GrLivArea,1stFlrSF,2ndFlrSF,GrLivArea.1,...,GarageType_Attchd,GarageType_Basment,GarageType_BuiltIn,GarageType_CarPort,GarageType_Detchd,GarageType_None,GarageFinish_Fin,GarageFinish_None,GarageFinish_RFn,GarageFinish_Unf
461,462,70,7200,7,9,1936,1135,575,560,1135,...,0,0,0,0,1,0,0,0,1,0
373,374,20,10634,5,6,1953,1319,1319,0,1319,...,1,0,0,0,0,0,0,0,0,1
1271,1272,20,9156,6,7,1968,1489,1489,0,1489,...,1,0,0,0,0,0,0,0,1,0
634,635,90,6979,6,5,1980,1056,1056,0,1056,...,0,0,0,0,1,0,0,0,0,1
1245,1246,80,12090,6,7,1984,1868,1140,728,1868,...,0,0,1,0,0,0,1,0,0,0

In [23]:
# do all the work on the training set

gbm.fit(X_train, y_train)

GradientBoostingRegressor()

In [24]:
#always score on the test set
gbm.score(X_test, y_test)

0.8840068837013959

In [25]:
# validation set
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.2, random_state=1985)

In [26]:
gbm.fit(X_train, y_train)

GradientBoostingRegressor()

In [27]:
gbm.score(X_val, y_val)

0.8786338964727649

In [28]:
from sklearn.model_selection import cross_val_score

In [29]:
scores = cross_val_score(estimator=gbm, X=X_train, y=y_train, cv=10)

In [30]:
scores

array([0.81944517, 0.9188566 , 0.87888591, 0.86741736, 0.93084098,
       0.89003065, 0.19116506, 0.81595128, 0.84190789, 0.93961805])

In [31]:
# most of data set is normal, but there is something wrong, giving low score

In [32]:
!pip install category_encoders

Collecting category_encoders
  Downloading category_encoders-2.2.2-py2.py3-none-any.whl (80 kB)
     |████████████████████████████████| 80 kB 2.8 MB/s eta 0:00:011
Requirement already satisfied: pandas>=0.21.1 in /opt/anaconda3/lib/python3.8/site-packages (from category_encoders) (1.0.5)
Requirement already satisfied: statsmodels>=0.9.0 in /opt/anaconda3/lib/python3.8/site-packages (from category_encoders) (0.11.1)
Requirement already satisfied: scipy>=1.0.0 in /opt/anaconda3/lib/python3.8/site-packages (from category_encoders) (1.5.0)
Requirement already satisfied: patsy>=0.5.1 in /opt/anaconda3/lib/python3.8/site-packages (from category_encoders) (0.5.1)
Requirement already satisfied: numpy>=1.14.0 in /opt/anaconda3/lib/python3.8/site-packages (from category_encoders) (1.18.5)
Requirement already satisfied: scikit-learn>=0.20.0 in /opt/anaconda3/lib/python3.8/site-packages (from category_encoders) (0.23.1)
Requirement already satisfied: python-dateutil>=2.6.1 in /opt/anaconda3/lib/python3.8/site-packages (from pandas>=0.21.1->category_encoders) (2.8.1)
Requirement already satisfied: pytz>=2017.2 in /opt/anaconda3/lib/python3.8/site-packages (from pandas>=0.21.1->category_encoders) (2020.1)
Requirement already satisfied: six in /opt/anaconda3/lib/python3.8/site-packages (from patsy>=0.5.1->category_encoders) (1.15.0)
Requirement already satisfied: joblib>=0.11 in /opt/anaconda3/lib/python3.8/site-packages (from scikit-learn>=0.20.0->category_encoders) (0.16.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /opt/anaconda3/lib/python3.8/site-packages (from scikit-learn>=0.20.0->category_encoders) (2.1.0)
Installing collected packages: category-encoders
Successfully installed category-encoders-2.2.2

In [34]:
import category_encoders as ce

In [35]:
ore = ce.OrdinalEncoder()

In [36]:
X_train

,Id,MSSubClass,LotArea,OverallQual,OverallCond,YearBuilt,GrLivArea,1stFlrSF,2ndFlrSF,GrLivArea.1,...,GarageType_Attchd,GarageType_Basment,GarageType_BuiltIn,GarageType_CarPort,GarageType_Detchd,GarageType_None,GarageFinish_Fin,GarageFinish_None,GarageFinish_RFn,GarageFinish_Unf
31,32,20,8544,5,6,1966,1228,1228,0,1228,...,1,0,0,0,0,0,0,0,0,1
771,772,20,8877,4,5,1951,1220,1220,0,1220,...,0,0,0,0,1,0,0,0,0,1
328,329,75,11888,6,6,1916,2134,1445,689,2134,...,0,0,0,0,1,0,0,0,0,1
706,707,20,115149,7,5,1971,1824,1824,0,1824,...,1,0,0,0,0,0,0,0,0,1
1235,1236,70,13132,5,5,1914,1784,892,892,1784,...,0,0,0,0,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
815,816,20,12137,7,5,1998,1661,1661,0,1661,...,1,0,0,0,0,0,0,0,1,0
790,791,120,3182,7,5,2005,1145,1145,0,1145,...,1,0,0,0,0,0,1,0,0,0
1342,1343,60,9375,8,5,2002,2169,1284,885,2169,...,1,0,0,0,0,0,0,0,1,0
331,332,20,8176,5,6,1958,1056,1056,0,1056,...,1,0,0,0,0,0,0,0,1,0
134,135,20,10335,5,6,1968,1721,1721,0,1721,...,1,0,0,0,0,0,0,0,1,0

In [43]:
X_train

,Id,MSSubClass,MSZoning,LotArea,Neighborhood,OverallQual,OverallCond,YearBuilt,GrLivArea,1stFlrSF,2ndFlrSF,GrLivArea.1,FullBath,HalfBath,GarageType,GarageYrBlt,GarageFinish,GarageCars
461,462,70,RL,7200,SWISU,7,9,1936,1135,575,560,1135,1,0,Detchd,1971.0,RFn,2
373,374,20,RL,10634,NAmes,5,6,1953,1319,1319,0,1319,1,0,Attchd,1953.0,Unf,1
1271,1272,20,RL,9156,NWAmes,6,7,1968,1489,1489,0,1489,2,0,Attchd,1968.0,RFn,2
634,635,90,RL,6979,OldTown,6,5,1980,1056,1056,0,1056,0,0,Detchd,1980.0,Unf,2
1245,1246,80,RL,12090,NWAmes,6,7,1984,1868,1140,728,1868,3,1,BuiltIn,1984.0,Fin,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
446,447,20,RL,16492,NAmes,6,6,1966,1888,1888,0,1888,2,1,Attchd,1966.0,Fin,2
1376,1377,30,RL,6292,SWISU,6,5,1930,790,790,0,790,1,0,Detchd,1925.0,Unf,1
1078,1079,120,RM,4435,CollgCr,6,5,2004,848,848,0,848,1,0,Attchd,2004.0,RFn,2
709,710,20,RL,7162,Sawyer,5,7,1966,904,904,0,904,1,0,Attchd,1966.0,Unf,1
1317,1318,120,FV,4230,Somerst,7,5,2006,1352,1352,0,1352,2,0,Attchd,2006.0,RFn,2

In [44]:
X_test

,Id,MSSubClass,MSZoning,LotArea,Neighborhood,OverallQual,OverallCond,YearBuilt,GrLivArea,1stFlrSF,2ndFlrSF,GrLivArea.1,FullBath,HalfBath,GarageType,GarageYrBlt,GarageFinish,GarageCars
1023,1024,120,RL,3182,Blmngtn,7,5,2005,1504,1504,0,1504,2,0,Attchd,2005.0,Fin,2
1253,1254,60,RL,17542,Veenker,7,7,1974,2167,1516,651,2167,2,1,Attchd,1974.0,RFn,2
1274,1275,50,RL,5362,Crawfor,5,6,1910,1250,661,589,1250,2,0,Detchd,1985.0,Unf,2
1185,1186,50,RL,9738,Edwards,5,7,1924,1221,949,272,1221,1,0,Attchd,1965.0,Unf,1
91,92,20,RL,8500,NAmes,5,3,1961,1235,1235,0,1235,1,0,Attchd,1961.0,Unf,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
739,740,60,RL,9313,CollgCr,7,5,2004,1728,864,864,1728,2,1,Attchd,2004.0,RFn,2
1434,1435,20,RL,17400,Mitchel,5,5,1977,1126,1126,0,1126,2,0,Attchd,1977.0,RFn,2
547,548,85,RL,7244,Mitchel,5,7,1970,768,768,0,768,1,0,Detchd,1987.0,Unf,2
1106,1107,20,RL,10357,SawyerW,7,5,1990,1442,1442,0,1442,2,0,Attchd,1990.0,Fin,2
130,131,60,RL,14200,NAmes,7,6,1966,2157,1216,941,2157,2,1,Attchd,1966.0,Fin,2

In [45]:
# transformed training set; will also transform test set
ore.fit_transform(X_train)

,Id,MSSubClass,MSZoning,LotArea,Neighborhood,OverallQual,OverallCond,YearBuilt,GrLivArea,1stFlrSF,2ndFlrSF,GrLivArea.1,FullBath,HalfBath,GarageType,GarageYrBlt,GarageFinish,GarageCars
461,462,70,1,7200,1,7,9,1936,1135,575,560,1135,1,0,1,1971.0,1,2
373,374,20,1,10634,2,5,6,1953,1319,1319,0,1319,1,0,2,1953.0,2,1
1271,1272,20,1,9156,3,6,7,1968,1489,1489,0,1489,2,0,2,1968.0,1,2
634,635,90,1,6979,4,6,5,1980,1056,1056,0,1056,0,0,1,1980.0,2,2
1245,1246,80,1,12090,3,6,7,1984,1868,1140,728,1868,3,1,3,1984.0,3,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
446,447,20,1,16492,2,6,6,1966,1888,1888,0,1888,2,1,2,1966.0,3,2
1376,1377,30,1,6292,1,6,5,1930,790,790,0,790,1,0,1,1925.0,2,1
1078,1079,120,2,4435,12,6,5,2004,848,848,0,848,1,0,2,2004.0,1,2
709,710,20,1,7162,6,5,7,1966,904,904,0,904,1,0,2,1966.0,2,1
1317,1318,120,4,4230,8,7,5,2006,1352,1352,0,1352,2,0,2,2006.0,1,2

In [46]:
ore.category_mapping

[{'col': 'MSZoning',
  'mapping': RL         1
  RM         2
  RH         3
  FV         4
  C (all)    5
  NaN       -2
  dtype: int64,
  'data_type': dtype('O')},
 {'col': 'Neighborhood',
  'mapping': SWISU       1
  NAmes       2
  NWAmes      3
  OldTown     4
  NridgHt     5
  Sawyer      6
  ClearCr     7
  Somerst     8
  SawyerW     9
  NPkVill    10
  BrkSide    11
  CollgCr    12
  Edwards    13
  Veenker    14
  Gilbert    15
  Crawfor    16
  NoRidge    17
  MeadowV    18
  Blmngtn    19
  Timber     20
  BrDale     21
  Mitchel    22
  StoneBr    23
  Blueste    24
  IDOTRR     25
  NaN        -2
  dtype: int64,
  'data_type': dtype('O')},
 {'col': 'GarageType',
  'mapping': Detchd     1
  Attchd     2
  BuiltIn    3
  2Types     4
  None       5
  Basment    6
  CarPort    7
  NaN       -2
  dtype: int64,
  'data_type': dtype('O')},
 {'col': 'GarageFinish',
  'mapping': RFn     1
  Unf     2
  Fin     3
  None    4
  NaN    -2
  dtype: int64,
  'data_type': dtype('O')}]

In [47]:
from sklearn.pipeline import make_pipeline

In [53]:
pipe = make_pipeline(ore, gbm)
ohe = ce.OneHotEncoder()
pipe2 = make_pipeline(ohe, gbm)

In [59]:
pipe2.fit(X_train, y_train)

Pipeline(steps=[('onehotencoder',
                 OneHotEncoder(cols=['MSZoning', 'Neighborhood', 'GarageType',
                                     'GarageFinish'])),
                ('gradientboostingregressor',
                 GradientBoostingRegressor(max_depth=4))])

In [60]:
pipe2.score(X_test, y_test)

0.8814392278566954

In [56]:
pipe.steps

[('ordinalencoder',
  OrdinalEncoder(cols=['MSZoning', 'Neighborhood', 'GarageType', 'GarageFinish'],
                 mapping=[{'col': 'MSZoning', 'data_type': dtype('O'),
                           'mapping': RL         1
  RM         2
  RH         3
  FV         4
  C (all)    5
  NaN       -2
  dtype: int64},
                          {'col': 'Neighborhood', 'data_type': dtype('O'),
                           'mapping': SWISU       1
  NAmes       2
  NWAmes      3
  OldTown     4
  NridgHt     5
  Sawyer      6
  ClearCr     7
  Somerst     8
  SawyerW     9
  NPkVill    10
  BrkSide    11
  CollgCr    12
  Edwards    13
  Veenker    14
  Gilbert    15
  Crawfor    16
  NoRidge    17
  MeadowV    18
  Blmngtn    19
  Timber     20
  BrDale     21
  Mitchel    22
  StoneBr    23
  Blueste    24
  IDOTRR     25
  NaN        -2
  dtype: int64},
                          {'col': 'GarageType', 'data_type': dtype('O'),
                           'mapping': Detchd     1
  Attchd     2
  BuiltIn    3
  2Types     4
  None       5
  Basment    6
  CarPort    7
  NaN       -2
  dtype: int64},
                          {'col': 'GarageFinish', 'data_type': dtype('O'),
                           'mapping': RFn     1
  Unf     2
  Fin     3
  None    4
  NaN    -2
  dtype: int64}])),
 ('gradientboostingregressor', GradientBoostingRegressor())]

In [64]:
pipe.steps[1][1].set_params(max_depth=3)

GradientBoostingRegressor()

In [65]:
scores2 = cross_val_score(estimator=pipe, X=X_train, y=y_train, cv=10)

In [63]:
scores.mean()

0.8454926053684227

In [66]:
# validation scores used to check if you are making improvements or not
# using pipelines make this quicker and easier

scores2.mean()

0.8485250485296426

In [68]:
pip install pdpbox

Collecting pdpbox
  Downloading PDPbox-0.2.0.tar.gz (57.7 MB)
     |████████████████████████████████| 57.7 MB 3.1 MB/s eta 0:00:01     |███████▉                        | 14.2 MB 3.5 MB/s eta 0:00:13     |█████████                       | 16.1 MB 3.1 MB/s eta 0:00:14     |██████████▉                     | 19.6 MB 3.1 MB/s eta 0:00:13     |███████████▌                    | 20.6 MB 3.1 MB/s eta 0:00:13     |█████████████▎                  | 23.8 MB 6.8 MB/s eta 0:00:05     |█████████████▉                  | 25.0 MB 6.8 MB/s eta 0:00:05
Requirement already satisfied: pandas in /opt/anaconda3/lib/python3.8/site-packages (from pdpbox) (1.0.5)
Requirement already satisfied: numpy in /opt/anaconda3/lib/python3.8/site-packages (from pdpbox) (1.18.5)
Requirement already satisfied: scipy in /opt/anaconda3/lib/python3.8/site-packages (from pdpbox) (1.5.0)
Requirement already satisfied: matplotlib>=2.1.2 in /opt/anaconda3/lib/python3.8/site-packages (from pdpbox) (3.2.2)
Requirement already satisfied: joblib in /opt/anaconda3/lib/python3.8/site-packages (from pdpbox) (0.16.0)
Requirement already satisfied: psutil in /opt/anaconda3/lib/python3.8/site-packages (from pdpbox) (5.7.0)
Requirement already satisfied: scikit-learn in /opt/anaconda3/lib/python3.8/site-packages (from pdpbox) (0.23.1)
Requirement already satisfied: python-dateutil>=2.6.1 in /opt/anaconda3/lib/python3.8/site-packages (from pandas->pdpbox) (2.8.1)
Requirement already satisfied: pytz>=2017.2 in /opt/anaconda3/lib/python3.8/site-packages (from pandas->pdpbox) (2020.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /opt/anaconda3/lib/python3.8/site-packages (from matplotlib>=2.1.2->pdpbox) (1.2.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /opt/anaconda3/lib/python3.8/site-packages (from matplotlib>=2.1.2->pdpbox) (2.4.7)
Requirement already satisfied: cycler>=0.10 in /opt/anaconda3/lib/python3.8/site-packages (from matplotlib>=2.1.2->pdpbox) (0.10.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /opt/anaconda3/lib/python3.8/site-packages (from scikit-learn->pdpbox) (2.1.0)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.8/site-packages (from python-dateutil>=2.6.1->pandas->pdpbox) (1.15.0)
Building wheels for collected packages: pdpbox
  Building wheel for pdpbox (setup.py) ... done
  Created wheel for pdpbox: filename=PDPbox-0.2.0-py3-none-any.whl size=57690722 sha256=1bf7110480b357fce4f1d65af52f1d1777e21f3b7b48fe9c1eb19b38e350fd93
  Stored in directory: /Users/imac/Library/Caches/pip/wheels/7f/7d/f5/136844ad90a5cfb60b92f6de7afadd0574042b6012a6d16e2b
Successfully built pdpbox
Installing collected packages: pdpbox
Successfully installed pdpbox-0.2.0
Note: you may need to restart the kernel to use updated packages.

In [69]:
pipe

Pipeline(steps=[('ordinalencoder',
                 OrdinalEncoder(cols=['MSZoning', 'Neighborhood', 'GarageType',
                                      'GarageFinish'],
                                mapping=[{'col': 'MSZoning',
                                          'data_type': dtype('O'),
                                          'mapping': RL         1
RM         2
RH         3
FV         4
C (all)    5
NaN       -2
dtype: int64},
                                         {'col': 'Neighborhood',
                                          'data_type': dtype('O'),
                                          'mapping': SWISU       1
NAmes       2
NWAmes      3
OldTown     4
NridgHt     5
Sawyer      6
ClearCr     7
Somerst     8
SawyerW     9
NPkVill    10
BrkSide    11
Coll...
Blmngtn    19
Timber     20
BrDale     21
Mitchel    22
StoneBr    23
Blueste    24
IDOTRR     25
NaN        -2
dtype: int64},
                                         {'col': 'GarageType',
                                          'data_type': dtype('O'),
                                          'mapping': Detchd     1
Attchd     2
BuiltIn    3
2Types     4
None       5
Basment    6
CarPort    7
NaN       -2
dtype: int64},
                                         {'col': 'GarageFinish',
                                          'data_type': dtype('O'),
                                          'mapping': RFn     1
Unf     2
Fin     3
None    4
NaN    -2
dtype: int64}])),
                ('gradientboostingregressor', GradientBoostingRegressor())])

In [70]:
X_copy = X_train.copy()

In [71]:
X_train["Prediction"] = pipe.predict(X_train)

ValueError: Number of features of the model must match the input. Model n_features is 55 and input n_features is 18