In [1]:
import pandas as pd
import numpy as np

In [2]:
cd /Users/imac/DAT07-28-AG/ClassMaterial/Unit2/Data

/Users/imac/DAT07-28-AG/ClassMaterial/Unit2/Data

In [3]:
df = pd.read_excel("superstore.xls")

In [4]:
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2014-110422,2014-01-21,2014-01-23,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
9990,9991,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332
9991,9992,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
9992,9993,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200
9993,9994,CA-2017-119914,2017-05-04,2017-05-09,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480

In [5]:
sales_mean = df.groupby("Sub-Category")[["Sales"]].mean()

In [6]:
sales_mean

                    Sales
Sub-Category
Accessories    215.974604
Appliances     230.755710
Art             34.068834
Binders        133.560560
Bookcases      503.859633
Chairs         532.332420
Copiers       2198.941618
Envelopes       64.867724
Fasteners       13.936774
Furnishings     95.825668
Labels          34.303055
Machines      1645.553313
Paper           57.284092
Phones         371.211534
Storage        264.590553
Supplies       245.650200
Tables         648.794771

In [7]:
sales_mean.rename({"Sales": "SubCatAvg"}, axis=1, inplace=True)

In [8]:
df = df.merge(sales_mean, left_on="Sub-Category", right_index=True)

In [9]:
df["PercentDiff"] = (df["Sales"] - df["SubCatAvg"]) / df["SubCatAvg"]

In [10]:
cust_avgs = df.groupby("Customer Name")["PercentDiff"].mean()*100

In [11]:
cust_avgs.sort_values(ascending=False)

Customer Name
Mitch Willingham        672.210825
Christopher Martinez    555.127205
Jenna Caffey            535.085743
Andy Reiter             396.344151
Adrian Barton           396.321356
                           ...
Lela Donovan            -84.431519
Susan Gilcrest          -84.973073
Cari Schnelling         -85.288547
Mitch Gastineau         -91.917354
Thais Sissman           -98.190708
Name: PercentDiff, Length: 793, dtype: float64

In [12]:
profit_mean = df.groupby("Sub-Category")[["Profit"]].mean()

In [13]:
profit_mean

                  Profit
Sub-Category
Accessories    54.111788
Appliances     38.922758
Art             8.200737
Binders        19.843574
Bookcases     -15.230509
Chairs         43.095894
Copiers       817.909190
Envelopes      27.418019
Fasteners       4.375660
Furnishings    13.645918
Labels         15.236962
Machines       29.432669
Paper          24.856620
Phones         50.073938
Storage        25.152277
Supplies       -6.258418
Tables        -55.565771

In [14]:
profit_mean.rename({"Profit": "SubCatProfitAvg"}, axis=1, inplace=True)

In [15]:
df = df.merge(profit_mean, left_on="Sub-Category", right_index=True)

In [16]:
df["PercentDiff"] = (df["Profit"] - df["SubCatProfitAvg"]) / df["SubCatProfitAvg"]

In [20]:
cust__profit_avgs = df.groupby("Customer Name")["PercentDiff"].mean()

In [21]:
cust__profit_avgs.sort_values(ascending=False)

Customer Name
Mitch Willingham        24.040565
Christopher Martinez    18.624369
Jim Radford             16.282799
Andy Reiter             13.739836
Adrian Barton           13.378266
                          ...
Luke Foster            -12.429651
Paul Knutson           -13.896034
Sharelle Roach         -13.952712
Grant Thornton         -21.260862
Cindy Stewart          -26.713990
Name: PercentDiff, Length: 793, dtype: float64

In [19]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,SubCatAvg,PercentDiff,SubCatProfitAvg
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,503.859633,-3.751950,-15.230509
27,28,US-2015-150630,2015-09-17,2015-09-21,Standard Class,TB-21520,Tracy Blumstein,Consumer,United States,Philadelphia,...,Furniture,Bookcases,"Riverside Palais Royal Lawyers Bookcase, Royal...",3083.4300,7,0.50,-1665.0522,503.859633,108.323479,-15.230509
38,39,CA-2015-117415,2015-12-27,2015-12-31,Standard Class,SN-20710,Steve Nguyen,Home Office,United States,Houston,...,Furniture,Bookcases,"Atlantic Metals Mobile 3-Shelf Bookcases, Cust...",532.3992,3,0.32,-46.9764,503.859633,2.084362,-15.230509
189,190,CA-2015-102281,2015-10-12,2015-10-14,First Class,MP-17470,Mark Packer,Home Office,United States,New York City,...,Furniture,Bookcases,"Atlantic Metals Mobile 4-Shelf Bookcases, Cust...",899.1360,4,0.20,112.3920,503.859633,-8.379399,-15.230509
192,193,CA-2015-102281,2015-10-12,2015-10-14,First Class,MP-17470,Mark Packer,Home Office,United States,New York City,...,Furniture,Bookcases,"Atlantic Metals Mobile 3-Shelf Bookcases, Cust...",626.3520,3,0.20,46.9764,503.859633,-4.084362,-15.230509

In [29]:
cd /Users/imac/DAT07-28-AG/ClassMaterial/Unit2/Data

/Users/imac/DAT07-28-AG/ClassMaterial/Unit2/Data

In [30]:
df = pd.read_excel("stocks.csv")

XLRDError: Unsupported format, or corrupt file: Expected BOF record; found b'Date,AAP'

In [24]:
df = pd.read_excel("stocks.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'stocks.csv'